config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :members

  get '/landing/:id' => 'pages#landing', as: :landing
  get '/thankyou' => 'pages#thankyou', as: :thankyou
  get '/admin' => 'pages#admin', as: :admin

end

app/models/member.rb
class Member < ActiveRecord::Base
  before_validation :initialize_preferences, on: :create
  
  store_accessor :preferences, ["subject", "region", "price", "start_date"]
  
  validates :email, presence: true

  #set list of preferences to be stored
  PREFERENCES = ["subject", "region", "price", "start_date"]

  def initialize_preferences 
    self.preferences = Hash[ PREFERENCES.map { |preference| [preference, []] }]
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def region_names 
    region.map { |region_id| Region.find_by_id(region_id).try(:name) }.compact
  end


  # using store_accessor is a much better way to have these getter/setter methods
  # - but this is fun to do if it ever makes sense :)
  #metaprogramming madness!!
  #define methods to easily check to see if a user has a given preference in their json object
  # PREFERENCES.each do |preference|
  #   define_method("prefers_#{preference}?") do |preference_type|

  #     if preferences["#{preference}"] && preferences["#{preference}"].include?("#{preference_type}")
  #       return true
  #     else
  #       return false
  #     end
  #   end
  # end

end

app/models/region.rb
class Region < ActiveRecord::Base
  has_and_belongs_to_many :trainings,  :join_table => :trainings_regions
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_and_belongs_to_many :trainings,  :join_table => :trainings_subjects
end

app/models/training.rb
class Training < ActiveRecord::Base
  has_and_belongs_to_many :subjects,  :join_table => :trainings_subjects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
before_action :set_member, only: [:update]


  def update
    # binding.remote_pry
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to thankyou_path, notice: 'Member was successfully updated.' }
      
      else
        @error = @member.errors.full_messages.to_sentence
        format.html { redirect_to landing_path(id: @member.id), alert: "Something went wrong. #{@error}" }
      end
    end
  end


  private

    # Use callbacks to share common setup or constraints between actions.
  def set_member
    @member = Member.find_by_id(params[:id])
  end

  def member_params
    params.require(:member).permit(:email, :first_name, :last_name, :phone, 
    # {"preferences"=>{"subject"=>"[\"math\", \"science\"]", "region"=>"[1, 2]", "price"=>"[\"free\"]", "start_date"=>""}

    #for prices, use ranges to define them.
    #region just store the ID
    #everything in the form actually stored somewhere
    #build out the user interaction
    #fill out starting date
    #create a constant, loop through everything on the front-end
    { preferences: [ {subject: []}, {region: []}, {price: []}, {start_date: []} ] } 
    )
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def admin
    @members = Member.all
  end

  def landing
    @member = Member.find_by_id(params[:id])

    @subjects = Subject.all
    @regions = Region.all

    return redirect_to root_path if @member.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_flash.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible text-center" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible text-center" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= alert %>
</div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
        <%= link_to "" do %>
          <%= image_tag "logos/logo-springest-low.png", class: "img-responsive logo" %>
        <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Landerly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render partial: "layouts/header" %>
  <%= render partial: "layouts/flash" %>
  
    <%= yield %>

  <%= render partial: "layouts/footer" %>

</body>
</html>

app/views/pages/admin.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8">

      <!-- note this is just for demo purposes -->
      <%= link_to "Back to landing page", landing_path(Member.last), class: "btn btn-primary" %>

      <h1>Admin</h1>

      <table class="table table-striped">
        <tr>
          <th>ID</th>
          <th>Full Name</th>
          <th>Email</th>
          <th>Subject(s)</th>
          <th>Region(s)</th>
          <th>Budget</th>
          <th>Start Date(s)</th>
        </tr>

        <% @members.each do |member| %>
          <tr>
            <td><%= member.id %></td>
            <td><%= member.full_name %></td>
            <td><%= member.email %></td>
            <td><%= member.subject.reject(&:empty?).join(", ") %></td>
            <td><%= member.region_names.join(", ") %></td>
            <td><%= member.price.reject(&:empty?).join(", ") %></td>
            <td><%= member.start_date.reject(&:empty?).join(", ") %></td>
          </tr>
        <% end %>
      </table>

    </div>
  </div>
</div>

app/views/pages/index.html.erb
<h1>Home Sweet Home!</h1>

app/views/pages/landing.html.erb
<div class="container">
  <div class="row">
    <div class="alert alert-success">
      Thanks for your response. Read on to see how we can solve this together!
    </div>
  </div>


  <div class="row">
    <div class="col-sm-10">
      <h1>You're searching for a course or training program.</h1>
      <p>Nice that you're so proactive! We'd love to help you along.
        One of our specialists can look at your profile, give you <%= link_to "", "free personal advice" %>
        and even process a course booking. Please specify what you're searching for below.</p>
      </div>
    </div>


    <div class="row">
      <div class="col-sm-2">
        <div class="thumbnail">
          <img src="http://lorempixel.com/g/150/150/animals/" alt="...">
          <div class="caption">
            <h3>Anny</h3>
          </div>
        </div>
      </div>

      <div class="col-sm-2">
        <div class="thumbnail">
          <img src="http://lorempixel.com/g/150/150/fashion/" alt="...">
          <div class="caption">
            <h3>Doron</h3>
          </div>
        </div>
      </div>

      <div class="col-sm-2">
        <div class="thumbnail">
          <img src="http://lorempixel.com/g/150/150/people/" alt="...">
          <div class="caption">
            <h3>Marlou</h3>
          </div>
        </div>
      </div>

      <div class="col-sm-2">
        <div class="thumbnail">
          <img src="http://lorempixel.com/g/150/150/cats/" alt="...">
          <div class="caption">
            <h3>Midas</h3>
          </div>
        </div>
      </div>
    </div>


    <div class="row">
      <div class="col-sm-10">
        <%= form_for @member, url: { controller: "members", action: "update" } do |f| %>

        <h2><%= @member.first_name %>, What are you looking for?</h2>
        <p>Be specific!</p>

        <div class="row">
          <%= f.fields_for :preferences do |p| %>

          <!-- Form group checkboxes for SUBJECT -->
          <div class="form-group form-inline clearfix">
            <%= p.label :subject, "Subject(s)", class: "control-label col-sm-2" %>      
            
            <%= hidden_field_tag "member[preferences][subject][]", nil %>
            <% @subjects.each do |subject| %>
              <%= label_tag do %>
              <input name="member[preferences][subject][]" type="checkbox" value="<%= subject.name %>" <% if @member.subject.include?(subject.name) %>checked<% end %> >
              <%= subject.name.capitalize %>
              <% end %>
            <% end %>

          </div>

          <!-- Form group checkboxes for REGION -->
          <div class="form-group form-inline clearfix">
            <%= p.label :region, "Region(s)", class: "control-label  col-sm-2" %>
            
            <!-- Add hidden field above all checkboxes with empty value. 
              It will be sent in case user didn't check any checkboxes. -->
            <%= hidden_field_tag "member[preferences][region][]", nil %>
            <% @regions.each do |region| %>
              <%= label_tag do %>
                <input name="member[preferences][region][]" type="checkbox" value="<%= region.id %>" <% if @member.region.include?("#{region.id}") %>checked<% end %> >
                <%= region.name.capitalize %>
              <% end %>
            <% end %>
            
          </div>

          <!-- Form group checkboxes for PRICE -->
          <div class="form-group form-inline clearfix">
          
            <%= p.label :price, "Price", class: "control-label col-sm-2" %>
            <%= hidden_field_tag "member[preferences][price][]", nil %>
            <%= label_tag do %>
            <input name="member[preferences][price][]" type="checkbox" value="free" <% if @member.price.include?('free') %>checked<% end %> >
            Free
            <% end %>

            <%= label_tag do %>
            <input name="member[preferences][price][]" type="checkbox" value="0-500" <% if @member.price.include?('0-500') %>checked<% end %>  >
            0-500
            <% end %>

            <%= label_tag do %>
            <input name="member[preferences][price][]" type="checkbox" value="500-1000" <% if @member.price.include?('500-1000') %>checked<% end %>  >
            500-1000
            <% end %>

          </div>

          <div class="form-group form-inline clearfix">
            <%= p.label :start_date, "Starting Date", class: "control-label col-sm-2" %>
            <%= hidden_field_tag "member[preferences][start_date][]", nil %>

            <%= label_tag do %>
            <input name="member[preferences][start_date][]" type="checkbox" value="2015-11-1"<% if @member.start_date.include?('2015-11-1') %>checked<% end %> >

              November 2015
            <% end %>

            <%= label_tag do %>
            <input name="member[preferences][start_date][]" type="checkbox" value="2015-12-1"<% if @member.start_date.include?('2015-12-1') %>checked<% end %> >

              December 2015
            <% end %>

            <%= label_tag do %>
            <input name="member[preferences][start_date][]" type="checkbox" value="2016-1-1"<% if @member.start_date.include?('2016-1-1') %>checked<% end %> >

              January 2016
            <% end %>
          </div>

          <% end %>

        </div>

        <!-- use this just to send an email to support -->
        <div class="form-group form-inline row">
          <%= label_tag :comments, "Comments", class: "control-label col-sm-2" %>
          <%= text_area_tag :comments, nil, cols: "40", rows: "8", class: "form-control col-sm-10" %>
        </div>

        <h2>And now what?</h2>
        <p>We're going to look at your specifications, do a little research and then contact you either via phone or email.</p>

        <div class="form-group form-inline clearfix">
          <%= f.label :phone, class: "control-label" %>
          <%= f.text_field :phone, class: "form-control" %>
        </div>

        <div class="form-group form-inline">
          <!-- use this for internal support - don't save in database -->

          <%= label_tag :requested_phonecall do %>
          <%= check_box_tag :requested_phonecall %>
          Yes, I'd like to receive a phonecall
          <% end %>
        </div>


        <%= f.submit "Help me out", class: "btn btn-success" %>
        <% end %>


      </div>
    </div>

  </div>

app/views/pages/thankyou.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8">

      <h1>Thank You!</h1>

      <%= link_to "See admin panel", admin_path, class: "btn btn-primary" %>

    </div>
  </div>
</div>